# Generated by Django 5.0.7 on 2024-11-08 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_semail_alter_student_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='9346096771', max_length=10, validators=[django.core.validators.RegexValidator('[6-9]\\d{9}')]),
        ),
    ]
